version = 0.1

[default.deploy.parameters]
stack_name = "drunk-detector-app"
resolve_s3 = true
s3_prefix = "drunk-detector-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"drunk-detector-app-bucket\""
image_repositories = []
